### ISSUE TITLE
No method matching Irrational{:log2π}

### ISSUE THREAD

**Issue by maxmouchet** [FluxML/Zygote.jl#521]
This seems similar to #309.

On Julia `v1.3`, Zygote `v0.4.7` and Distributions `v0.22.4`:
```julia
using Distributions, Zygote

f(x) = logpdf(Normal(), x)
f(0.0) # -0.9189385332046728
f'(0.0)
# MethodError: no method matching Irrational{:log2π}(::Int64)
# Closest candidates are:
#  Irrational{:log2π}(::T) where T<:Number at boot.jl:718
#  Irrational{:log2π}() where sym at irrationals.jl:18
#  Irrational{:log2π}(!Matched::Complex) where T<:Real at complex.jl:37
```

**Comment by jessebett** [comment]
Yes, also getting this bug trying to differentiate through Normals

**Comment by mohamed82008** [comment]
See https://github.com/JuliaLang/julia/pull/34773. If you copy the code from that PR, the error should go away.

**Comment by mohamed82008** [comment]
Also the next release of DistributionsAD.jl will fix this.

**Comment by jessebett** [comment]
Okay but can you give a previous version of Distributions that doesn't have this error? Working on an assignment starter code and students won't be expected to patch julia...

**Comment by mohamed82008** [comment]
I am not sure which version. You can possibly make a file for them to include directly in their code. If you use the DistributionsAD#master now, your code should work. And in about week, a new release will be made.

**Comment by jessebett** [comment]
I'll try pinning DistributionsAD#master now

**Comment by mohamed82008** [comment]
Or just pin DiffRules to 1.0.0 instead.

**Comment by mohamed82008** [comment]
If you need nothing else from DistributionsAD.

**Comment by mohamed82008** [comment]
If Zygote uses Compat.jl, this issue should be solved.

**Comment by CarloLucibello** [comment]
@mohamed82008  `using DistributionsAD` the OP example is still not working. How am I supposed to use DistributionsAD?

**Comment by maxmouchet** [comment]
On Julia `v.1.4.1`, Zygote `v0.4.20`, Distributions `v0.23.2` and DistributionsAD `v0.5.3`:

```
using Distributions, DistributionsAD, Zygote

f(x) = logpdf(Normal(), x)
f(0.0) # -0.9189385332046728
f'(0.0) # -0.0
```

**Comment by NightMachinary** [comment]
I get this error on `Zygote 0.5.3` and `julia version 1.4.1`:
```
julia> function poi(λ, x)
           ((ℯ^-λ)*(λ^x))/factorial(x)
       end
poi (generic function with 1 method)

julia> h(x) = poi(1,1) + x
h (generic function with 1 method)

julia> h(1)
1.3678794411714423

julia> h'(1)
ERROR: MethodError: no method matching Irrational{:ℯ}(::Int64)
Closest candidates are:
  Irrational{:ℯ}(::T) where T<:Number at boot.jl:715
  Irrational{:ℯ}() where sym at irrationals.jl:18
  Irrational{:ℯ}(::Complex) where T<:Real at complex.jl:37
  ...
Stacktrace:
 [1] convert(::Type{Irrational{:ℯ}}, ::Int64) at ./number.jl:7
 [2] one(::Type{Irrational{:ℯ}}) at ./number.jl:276
 [3] one(::Irrational{:ℯ}) at ./number.jl:277
 [4] (::ChainRules.var"#583#^_pullback#151"{Irrational{:ℯ},Int64,Float64})(::Float64) at /Users/evar/.julia/packages/ChainRulesCore/b8RFI/src/rule_definition_tools.jl:195
 [5] ZBack at /Users/evar/.julia/packages/Zygote/iFibI/src/compiler/chainrules.jl:75 [inlined]
 [6] poi at ./REPL[89]:2 [inlined]
 [7] (::typeof(∂(poi)))(::Float64) at /Users/evar/.julia/packages/Zygote/iFibI/src/compiler/interface2.jl:0
 [8] h at ./REPL[90]:1 [inlined]
 [9] (::typeof(∂(h)))(::Float64) at /Users/evar/.julia/packages/Zygote/iFibI/src/compiler/interface2.jl:0
 [10] (::Zygote.var"#41#42"{typeof(∂(h))})(::Float64) at /Users/evar/.julia/packages/Zygote/iFibI/src/compiler/interface.jl:45
 [11] gradient(::Function, ::Int64) at /Users/evar/.julia/packages/Zygote/iFibI/src/compiler/interface.jl:54
 [12] (::Zygote.var"#43#44"{typeof(h)})(::Int64) at /Users/evar/.julia/packages/Zygote/iFibI/src/compiler/interface.jl:57
 [13] top-level scope at REPL[92]:1
```

**Comment by sethaxen** [comment]
I'm pretty sure this is the offending line of code, and yes, this should be fixed once `one(::Irrational)` works: https://github.com/JuliaDiff/ChainRules.jl/blob/v0.7.12/src/rulesets/Base/fastmath_able.jl#L144
